version: '3.1'

services:

  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hospital
    ports:
      - 8082:5432