version: '3.8'

services:

  postgresql:
    container_name: postgresql
    image: postgres:10.5
    restart: always
    volumes:
      - ./backup/hospital.sql:/docker-entrypoint-initdb.d/hospital.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hospital
      #POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - 8082:5432